In [631]:
import pandas as pd
import plotly.express as px

## Passo 1: Carregamento e Exploração Inicial

1. Carregar os três arquivos: Gerentes.xlsx, Vendas.xlsx e Vendas - Dez.csv.
2. Visualizar as primeiras linhas de cada base para entender a estrutura.
3. Conferir o tipo de dado de cada coluna.

In [632]:
df_gerentes = pd.read_excel('/content/drive/MyDrive/DATA PYHON 2604/Vendas/Gerentes.xlsx')

df_gerentes.head()

                 ID Loja  Gerente
0       Loja São Paulo 1    Paulo
1       Loja São Paulo 2    Joana
2       Loja São Paulo 3    Maria
3          Loja Campinas  Letícia
4  Loja Rio de Janeiro 1    Fábio

In [633]:
df_vendas = pd.read_excel('/content/drive/MyDrive/DATA PYHON 2604/Vendas/Vendas.xlsx', parse_dates=['Data'])

df_vendas.head()

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Valor Custo
0,1,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1,R$ 358.0,358.0,R$ 322.79
1,1,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2,R$ 180.0,360.0,R$ 134.32
2,1,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1,R$ 368.0,368.0,R$ 339.85
3,2,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3,R$ 250.0,750.0,R$ 231.65
4,2,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1,R$ 70.0,70.0,R$ 43.84

In [634]:
df_vendas_dez = pd.read_csv('/content/drive/MyDrive/DATA PYHON 2604/Vendas/Venda - Dez.csv', parse_dates=['Data'])

df_vendas_dez.head()

,Unnamed: 0,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Valor_Unitario_Num,Valor Custo
0,0,65014,2023-12-01,Loja Porto Alegre,Kit Teclado e Mouse Sem Fio,5,114,570,114,85.07
1,1,65014,2023-12-01,Loja Porto Alegre,Mouse sem Fio Microsoft,1,269,269,269,168.28
2,2,65016,2023-12-01,Loja São Paulo 2,Mouse Pad Colorido,2,363,726,363,148.97
3,3,65016,2023-12-01,Loja São Paulo 2,Mouse sem Fio Microsoft,1,250,250,250,156.40
4,4,65017,2023-12-01,Loja Fortaleza,Teclado sem Fio Megaware,3,92,276,92,68.63

In [635]:
df_gerentes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID Loja  14 non-null     object
 1   Gerente  14 non-null     object
dtypes: object(2)
memory usage: 356.0+ bytes

In [636]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93910 entries, 0 to 93909
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Código Venda    93910 non-null  int64
 1   Data            93910 non-null  datetime64[ns]
 2   ID Loja         93910 non-null  object
 3   Produto         93910 non-null  object
 4   Quantidade      93910 non-null  int64
 5   Valor Unitário  93910 non-null  object
 6   Valor Final     93766 non-null  float64
 7   Valor Custo     93910 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 5.7+ MB

In [637]:
df_vendas_dez.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7089 entries, 0 to 7088
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          7089 non-null   int64
 1   Código Venda        7089 non-null   int64
 2   Data                7089 non-null   datetime64[ns]
 3   ID Loja             7089 non-null   object
 4   Produto             7089 non-null   object
 5   Quantidade          7089 non-null   int64
 6   Valor Unitário      7089 non-null   int64
 7   Valor Final         7089 non-null   int64
 8   Valor_Unitario_Num  7089 non-null   int64
 9   Valor Custo         7089 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(6), object(2)
memory usage: 554.0+ KB

## Passo 2: Consolidação e Limpeza dos Dados

4. Limpar e converter as colunas valor_final e Preço Unitário para valores numéricos.
5. Recalcular valores nulos de valor_final usando a fórmula: valor_final = Quantidade ×
Preço Unitário.
6. Unificar as três bases de vendas em um único conjunto de dados.

In [638]:
nome_colunas = df_vendas.columns
print(type(nome_colunas))
print(nome_colunas)

df_vendas.columns = list(i.strip().lower().replace(' ','_').replace('á', 'a').replace('ó','o') for i in nome_colunas)
print(df_vendas.columns)
df_vendas

<class 'pandas.core.indexes.base.Index'>
Index(['Código Venda', 'Data', 'ID Loja', 'Produto', 'Quantidade',
       'Valor Unitário', 'Valor Final', 'Valor Custo'],
      dtype='object')
Index(['codigo_venda', 'data', 'id_loja', 'produto', 'quantidade',
       'valor_unitario', 'valor_final', 'valor_custo'],
      dtype='object')

,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_custo
0,1,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1,R$ 358.0,358.0,R$ 322.79
1,1,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2,R$ 180.0,360.0,R$ 134.32
2,1,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1,R$ 368.0,368.0,R$ 339.85
3,2,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3,R$ 250.0,750.0,R$ 231.65
4,2,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1,R$ 70.0,70.0,R$ 43.84
...,...,...,...,...,...,...,...,...
93905,65012,2023-11-30,Loja Rio de Janeiro 2,Memória DDR 3 Seagate 8 Gb,2,R$ 270.0,NaN,R$ 250.23
93906,65013,2023-11-30,Loja João Pessoa,Calculadora Cientifica HP,2,R$ 140.0,NaN,R$ 100.24
93907,65013,2023-11-30,Loja João Pessoa,Mousepad Gamer,3,R$ 72.0,216.0,R$ 32.32
93908,65014,2023-11-30,Loja Porto Alegre,Calculadora Cientifica HP,5,R$ 140.0,700.0,R$ 100.24
93909,65014,2023-11-30,Loja Porto Alegre,Memória DDR 4 Seagate 4 Gb,4,R$ 250.0,1000.0,R$ 231.65

In [639]:
nome_colunas = df_vendas_dez.columns
print(type(nome_colunas))
print(nome_colunas)

df_vendas_dez.columns = list(i.strip().lower().replace(' ','_').replace('á', 'a').replace('ó','o') for i in nome_colunas)
print(df_vendas_dez.columns)
df_vendas_dez

<class 'pandas.core.indexes.base.Index'>
Index(['Unnamed: 0', 'Código Venda', 'Data', 'ID Loja', 'Produto',
       'Quantidade', 'Valor Unitário', 'Valor Final', 'Valor_Unitario_Num',
       'Valor Custo'],
      dtype='object')
Index(['unnamed:_0', 'codigo_venda', 'data', 'id_loja', 'produto',
       'quantidade', 'valor_unitario', 'valor_final', 'valor_unitario_num',
       'valor_custo'],
      dtype='object')

,unnamed:_0,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_unitario_num,valor_custo
0,0,65014,2023-12-01,Loja Porto Alegre,Kit Teclado e Mouse Sem Fio,5,114,570,114,85.07
1,1,65014,2023-12-01,Loja Porto Alegre,Mouse sem Fio Microsoft,1,269,269,269,168.28
2,2,65016,2023-12-01,Loja São Paulo 2,Mouse Pad Colorido,2,363,726,363,148.97
3,3,65016,2023-12-01,Loja São Paulo 2,Mouse sem Fio Microsoft,1,250,250,250,156.40
4,4,65017,2023-12-01,Loja Fortaleza,Teclado sem Fio Megaware,3,92,276,92,68.63
...,...,...,...,...,...,...,...,...,...,...
7084,7084,69996,2023-12-26,Loja Rio de Janeiro 1,Mouse Pad Colorido,2,102,204,102,41.86
7085,7085,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,4,270,1080,270,247.67
7086,7086,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,1,87,87,87,79.80
7087,7087,69997,2023-12-26,Loja João Pessoa,HD SSD Kingston 1 Tb,1,108,108,108,96.30
7088,7088,69997,2023-12-26,Loja João Pessoa,Mouse Pad Colorido,2,133,266,133,54.58

In [640]:
nome_colunas = df_gerentes.columns
print(type(nome_colunas))
print(nome_colunas)

df_gerentes.columns = list(i.strip().lower().replace(' ','_').replace('á', 'a').replace('ó','o') for i in nome_colunas)
print(df_gerentes.columns)
df_gerentes

<class 'pandas.core.indexes.base.Index'>
Index(['ID Loja', 'Gerente'], dtype='object')
Index(['id_loja', 'gerente'], dtype='object')

                  id_loja   gerente
0        Loja São Paulo 1     Paulo
1        Loja São Paulo 2     Joana
2        Loja São Paulo 3     Maria
3           Loja Campinas   Letícia
4   Loja Rio de Janeiro 1     Fábio
5   Loja Rio de Janeiro 2     Luiza
6      Loja Florianópolis     Julia
7             Loja Recife    Nicole
8           Loja Blumenau     André
9          Loja Fortaleza      João
10       Loja João Pessoa    Marcus
11             Loja Natal    Amanda
12      Loja Porto Alegre     Carol
13           Loja Maringá  Andressa

In [641]:
nome_colunas = df_vendas_dez.columns
print(type(nome_colunas))
print(nome_colunas)

df_vendas_dez.columns = list(i.strip().lower().replace(' ','_').replace('á', 'a').replace('ó','o') for i in nome_colunas)
print(df_vendas_dez.columns)
df_vendas_dez

<class 'pandas.core.indexes.base.Index'>
Index(['unnamed:_0', 'codigo_venda', 'data', 'id_loja', 'produto',
       'quantidade', 'valor_unitario', 'valor_final', 'valor_unitario_num',
       'valor_custo'],
      dtype='object')
Index(['unnamed:_0', 'codigo_venda', 'data', 'id_loja', 'produto',
       'quantidade', 'valor_unitario', 'valor_final', 'valor_unitario_num',
       'valor_custo'],
      dtype='object')

,unnamed:_0,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_unitario_num,valor_custo
0,0,65014,2023-12-01,Loja Porto Alegre,Kit Teclado e Mouse Sem Fio,5,114,570,114,85.07
1,1,65014,2023-12-01,Loja Porto Alegre,Mouse sem Fio Microsoft,1,269,269,269,168.28
2,2,65016,2023-12-01,Loja São Paulo 2,Mouse Pad Colorido,2,363,726,363,148.97
3,3,65016,2023-12-01,Loja São Paulo 2,Mouse sem Fio Microsoft,1,250,250,250,156.40
4,4,65017,2023-12-01,Loja Fortaleza,Teclado sem Fio Megaware,3,92,276,92,68.63
...,...,...,...,...,...,...,...,...,...,...
7084,7084,69996,2023-12-26,Loja Rio de Janeiro 1,Mouse Pad Colorido,2,102,204,102,41.86
7085,7085,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,4,270,1080,270,247.67
7086,7086,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,1,87,87,87,79.80
7087,7087,69997,2023-12-26,Loja João Pessoa,HD SSD Kingston 1 Tb,1,108,108,108,96.30
7088,7088,69997,2023-12-26,Loja João Pessoa,Mouse Pad Colorido,2,133,266,133,54.58

In [642]:
# 4) Limpar e converter as colunas valor_final e Preço Unitário para valores numéricos.

In [643]:
 # alterando coluna int para float

df_vendas['valor_final'] = df_vendas['valor_final'].astype(float)
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93910 entries, 0 to 93909
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   codigo_venda    93910 non-null  int64
 1   data            93910 non-null  datetime64[ns]
 2   id_loja         93910 non-null  object
 3   produto         93910 non-null  object
 4   quantidade      93910 non-null  int64
 5   valor_unitario  93910 non-null  object
 6   valor_final     93766 non-null  float64
 7   valor_custo     93910 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 5.7+ MB

In [644]:
# 5) Recalcular valores nulos de valor_final usando a fórmula: valor_final = Quantidade × Preço Unitário.

In [645]:
df_vendas.isnull().sum()

codigo_venda        0
data                0
id_loja             0
produto             0
quantidade          0
valor_unitario      0
valor_final       144
valor_custo         0
dtype: int64

In [646]:
df_vendas_dez.isnull().sum()

unnamed:_0            0
codigo_venda          0
data                  0
id_loja               0
produto               0
quantidade            0
valor_unitario        0
valor_final           0
valor_unitario_num    0
valor_custo           0
dtype: int64

In [647]:
df_gerentes.isnull().sum()

id_loja    0
gerente    0
dtype: int64

In [648]:
# retirando o 'R$' do valor_unitario para converter em float
df_vendas['valor_unitario'] = df_vendas['valor_unitario'].str.replace('R$ ', '')

In [649]:
df_vendas['valor_custo'] = df_vendas['valor_custo'].str.replace('R$ ', '')

In [650]:
df_vendas['valor_unitario'] = df_vendas['valor_unitario'].astype(float)
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93910 entries, 0 to 93909
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   codigo_venda    93910 non-null  int64
 1   data            93910 non-null  datetime64[ns]
 2   id_loja         93910 non-null  object
 3   produto         93910 non-null  object
 4   quantidade      93910 non-null  int64
 5   valor_unitario  93910 non-null  float64
 6   valor_final     93766 non-null  float64
 7   valor_custo     93910 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 5.7+ MB

In [651]:
df_vendas['valor_custo'] = df_vendas['valor_custo'].astype(float)
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93910 entries, 0 to 93909
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   codigo_venda    93910 non-null  int64
 1   data            93910 non-null  datetime64[ns]
 2   id_loja         93910 non-null  object
 3   produto         93910 non-null  object
 4   quantidade      93910 non-null  int64
 5   valor_unitario  93910 non-null  float64
 6   valor_final     93766 non-null  float64
 7   valor_custo     93910 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(2)
memory usage: 5.7+ MB

In [652]:
df_vendas_dez['valor_final'] = df_vendas_dez['valor_final'].astype(float)
df_vendas_dez.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7089 entries, 0 to 7088
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   unnamed:_0          7089 non-null   int64
 1   codigo_venda        7089 non-null   int64
 2   data                7089 non-null   datetime64[ns]
 3   id_loja             7089 non-null   object
 4   produto             7089 non-null   object
 5   quantidade          7089 non-null   int64
 6   valor_unitario      7089 non-null   int64
 7   valor_final         7089 non-null   float64
 8   valor_unitario_num  7089 non-null   int64
 9   valor_custo         7089 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(5), object(2)
memory usage: 554.0+ KB

In [653]:
df_vendas_dez['valor_unitario'] = df_vendas_dez['valor_unitario'].astype(float)
df_vendas_dez.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7089 entries, 0 to 7088
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   unnamed:_0          7089 non-null   int64
 1   codigo_venda        7089 non-null   int64
 2   data                7089 non-null   datetime64[ns]
 3   id_loja             7089 non-null   object
 4   produto             7089 non-null   object
 5   quantidade          7089 non-null   int64
 6   valor_unitario      7089 non-null   float64
 7   valor_final         7089 non-null   float64
 8   valor_unitario_num  7089 non-null   int64
 9   valor_custo         7089 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(2)
memory usage: 554.0+ KB

In [654]:
df_vendas['valor_final'] = (df_vendas['quantidade'] * df_vendas['valor_unitario']).round(2)

In [655]:
df_vendas_dez['valor_final'] = (df_vendas_dez['quantidade'] * df_vendas_dez['valor_unitario']).round(2)

In [656]:
df_vendas.duplicated().sum()

np.int64(1151)

In [657]:
# 6) Unificar as três bases de vendas em um único conjunto de dados.

In [658]:
# JUNÇÃO DOS DADOS

df_vendas_final = pd.concat([df_vendas, df_vendas_dez], axis=0, join='inner')
display(df_vendas_final)
df_vendas_final.info()

,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_custo
0,1,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1,358.0,358.0,322.79
1,1,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2,180.0,360.0,134.32
2,1,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1,368.0,368.0,339.85
3,2,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3,250.0,750.0,231.65
4,2,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1,70.0,70.0,43.84
...,...,...,...,...,...,...,...,...
7084,69996,2023-12-26,Loja Rio de Janeiro 1,Mouse Pad Colorido,2,102.0,204.0,41.86
7085,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,4,270.0,1080.0,247.67
7086,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,1,87.0,87.0,79.80
7087,69997,2023-12-26,Loja João Pessoa,HD SSD Kingston 1 Tb,1,108.0,108.0,96.30
7088,69997,2023-12-26,Loja João Pessoa,Mouse Pad Colorido,2,133.0,266.0,54.58

<class 'pandas.core.frame.DataFrame'>
Index: 100999 entries, 0 to 7088
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   codigo_venda    100999 non-null  int64
 1   data            100999 non-null  datetime64[ns]
 2   id_loja         100999 non-null  object
 3   produto         100999 non-null  object
 4   quantidade      100999 non-null  int64
 5   valor_unitario  100999 non-null  float64
 6   valor_final     100999 non-null  float64
 7   valor_custo     100999 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(2)
memory usage: 6.9+ MB

In [659]:
# MESCLAGEM

df_final = df_vendas_final.merge(df_gerentes, on=['id_loja'],how='inner')

# SELECT * FROM df_vendas_final
# INNER JOIN df_gerentes ON (df_vendas_final.'id_loja' = df_gerentes.'id_loja')

df_final.head(10)

,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_custo,gerente
0,1,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1,358.0,358.0,322.79,Paulo
1,1,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2,180.0,360.0,134.32,Paulo
2,1,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1,368.0,368.0,339.85,Paulo
3,2,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3,250.0,750.0,231.65,Paulo
4,2,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1,70.0,70.0,43.84,Paulo
5,3,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,1,250.0,250.0,231.65,Paulo
6,5,2023-01-02,Loja São Paulo 2,Teclado sem Fio Microsoft,1,170.0,170.0,110.24,Joana
7,6,2023-01-02,Loja São Paulo 2,Mesa Digitalizadora,4,210.0,840.0,149.26,Joana
8,7,2023-01-02,Loja São Paulo 1,Fone de Ouvido sem Fio,1,116.0,116.0,79.69,Paulo
9,7,2023-01-02,Loja São Paulo 1,Fone Stéreo sem Fio Microsoft,1,105.0,105.0,72.10,Paulo

## Passo 3: Análise Descritiva e Perguntas de Negócio
7. Qual foi o faturamento analisado?
8. Qual loja teve o maior faturamento? Grafico com as 5 primeiras lojas de barra.
9. Qual produto foi o mais vendido em quantidade? Grafico com os 3 primeiros barra.
10. Qual produto foi o menos vendido em quantidade?
11. Qual produto gerou a maior receita?
12. Qual foi o lucro total e a margem de lucro geral?

In [661]:
df_final.drop_duplicates(inplace=True)
df_final.duplicated().sum()

np.int64(0)

In [689]:
df_final['valor_final'].sum()
faturamento = df_final['valor_final'].sum()

faturamento

np.float64(45468736.0)

In [662]:
df_final['lucro'] = (df_final['valor_unitario'] - df_final['valor_custo']) * df_final['quantidade']
df_final

,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_custo,gerente,lucro
0,1,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1,358.0,358.0,322.79,Paulo,35.21
1,1,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2,180.0,360.0,134.32,Paulo,91.36
2,1,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1,368.0,368.0,339.85,Paulo,28.15
3,2,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3,250.0,750.0,231.65,Paulo,55.05
4,2,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1,70.0,70.0,43.84,Paulo,26.16
...,...,...,...,...,...,...,...,...,...,...
100994,69996,2023-12-26,Loja Rio de Janeiro 1,Mouse Pad Colorido,2,102.0,204.0,41.86,Fábio,120.28
100995,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,4,270.0,1080.0,247.67,Fábio,89.32
100996,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,1,87.0,87.0,79.80,Fábio,7.20
100997,69997,2023-12-26,Loja João Pessoa,HD SSD Kingston 1 Tb,1,108.0,108.0,96.30,Marcus,11.70
100998,69997,2023-12-26,Loja João Pessoa,Mouse Pad Colorido,2,133.0,266.0,54.58,Marcus,156.84

In [663]:
df_final['margem_lucro'] = (((df_final['valor_unitario'] - df_final['valor_custo']) / df_final['valor_unitario']) * 100).round(2)
df_final

,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_custo,gerente,lucro,margem_lucro
0,1,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1,358.0,358.0,322.79,Paulo,35.21,9.84
1,1,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2,180.0,360.0,134.32,Paulo,91.36,25.38
2,1,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1,368.0,368.0,339.85,Paulo,28.15,7.65
3,2,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3,250.0,750.0,231.65,Paulo,55.05,7.34
4,2,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1,70.0,70.0,43.84,Paulo,26.16,37.37
...,...,...,...,...,...,...,...,...,...,...,...
100994,69996,2023-12-26,Loja Rio de Janeiro 1,Mouse Pad Colorido,2,102.0,204.0,41.86,Fábio,120.28,58.96
100995,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,4,270.0,1080.0,247.67,Fábio,89.32,8.27
100996,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,1,87.0,87.0,79.80,Fábio,7.20,8.28
100997,69997,2023-12-26,Loja João Pessoa,HD SSD Kingston 1 Tb,1,108.0,108.0,96.30,Marcus,11.70,10.83
100998,69997,2023-12-26,Loja João Pessoa,Mouse Pad Colorido,2,133.0,266.0,54.58,Marcus,156.84,58.96

In [664]:
# 7) Qual foi o faturamento analisado?

faturamento_lojas = df_final.groupby('id_loja')[['valor_final']].sum().reset_index()
faturamento_lojas.head()

              id_loja  valor_final
0       Loja Blumenau    1875413.0
1       Loja Campinas    1867784.0
2  Loja Florianópolis    1817117.0
3      Loja Fortaleza    1862791.0
4    Loja João Pessoa    1860334.0

In [665]:
faturamento_lojas = df_final.groupby('id_loja')['valor_final'].sum().sort_values(ascending=False).reset_index()
faturamento_lojas.head()

faturamento_lojas_top5 = faturamento_lojas.head()

display(faturamento_lojas_top5)

                 id_loja  valor_final
0       Loja São Paulo 3    7130618.0
1       Loja São Paulo 1    5532358.0
2  Loja Rio de Janeiro 2    5505854.0
3       Loja São Paulo 2    5490632.0
4  Loja Rio de Janeiro 1    5331597.0

In [666]:
# 8) Qual loja teve o maior faturamento? Grafico com as 5 primeiras lojas de barra.

fig = px.bar(faturamento_lojas_top5, x='id_loja', y='valor_final', title='Faturamento por Loja', text=faturamento_lojas_top5['valor_final'], color='valor_final', color_continuous_scale=px.colors.qualitative.Set1)

fig.show()

In [667]:
# 9) Qual produto foi o mais vendido em quantidade? Grafico com os 3 primeiros barra.

produto_mais = df_final.groupby('produto')['quantidade'].sum().sort_values(ascending=False).reset_index()

display(produto_mais)

                             produto  quantidade
0         Memória DDR 4 Seagate 4 Gb       36251
1         Memória DDR 3 Seagate 8 Gb       13674
2                 Mouse Pad Colorido       12359
3          Calculadora Cientifica HP       11170
4                Mesa Digitalizadora       10783
5            Roteador 300 Mbps Cisco       10777
6                     Mousepad Gamer       10097
7           Roteador 300 Mbps Tplink       10062
8            Mouse com Fio Microsoft        9961
9        Kit Teclado e Mouse Sem Fio        8915
10        Cartucho de Tinta HP BK123        8432
11            Fone de Ouvido sem Fio        8299
12     Fone Stéreo sem Fio Microsoft        6848
13      Memória DDR 4 Kingstone 8 Gb        5113
14              HD SSD Kingston 1 Tb        5008
15             HD SSD Samsung 256 Gb        4954
16              HD SSD Maxtel 750 Gb        4676
17            HD SSD Kingston 500 Gb        3514
18             Teclado sem Fio Multi        2508
19             Teclado Gamer com Led        2498
20          Teclado sem Fio Megaware        2445
21           Mouse sem Fio Microsoft        2443
22       Fone de Ouvido Bluetooth HP        2383
23             Mouse Bluetooth Multi        1893
24         Teclado sem Fio Microsoft        1768
25             HD SSD Seagate 500 Gb        1720
26                Teclado sem Fio HP        1696
27  Cartucho de Tinta Epson CIAN 735        1692
28    Fone de Ouvido Bluetooth Multi        1681
29   Mouse sem Fio "Turma da Mônica"        1679
30     Mouse sem Fio "Os Vingadores"        1675
31    Fone de Ouvido Bluetooth Loggi        1671
32                HD SSD Maxtel 1 Tb        1666
33            Mouse Anatomico Maxtel        1632
34                  Mouse sem Fio HP        1615
35             HD SSD Seagate 750 Gb        1609
36               HD SSD Seagate 1 Tb        1601

In [668]:
top_produtos = df_final.groupby('produto')['quantidade'].sum().sort_values(ascending=False).reset_index()
top_produtos.head(3)
fig = px.bar(top_produtos.head(3), x='produto', y='quantidade', text=top_produtos['quantidade'].head(3), color='produto')
fig.update_traces(textposition='outside')
fig.show()

In [669]:
# 10) Qual produto foi o menos vendido em quantidade?

menos_vendido = top_produtos['produto'].tail(1)
print(f'Produto menos vendido: {menos_vendido}')

Produto menos vendido: 36    HD SSD Seagate 1 Tb
Name: produto, dtype: object

In [686]:
# Qual foi o lucro total e a margem de lucro geral?

receita = df_final['lucro'].sum()
print(f'Receita Total: {receita:,.2f}')

margem_geral = receita / faturamento * 100
print(f'Lucro Geral: {margem_geral:.2f} %')

Receita Total: 8,002,729.42
Lucro Geral: 17.60 %

## Passo 4: Gerentes
13. Qual foi o mês com maior faturamento? Grafico de linha
14. Quais foram os produtos mais vendidos por cada gerente? Grafico de arvore

In [681]:
# Qual foi o mês com maior faturamento? Grafico de linha

df_final['ano - mes'] = df_final['data'].dt.to_period('M')
df_final

,codigo_venda,data,id_loja,produto,quantidade,valor_unitario,valor_final,valor_custo,gerente,lucro,margem_lucro,ano - mes
0,1,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1,358.0,358.0,322.79,Paulo,35.21,9.84,2023-01
1,1,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2,180.0,360.0,134.32,Paulo,91.36,25.38,2023-01
2,1,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1,368.0,368.0,339.85,Paulo,28.15,7.65,2023-01
3,2,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3,250.0,750.0,231.65,Paulo,55.05,7.34,2023-01
4,2,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1,70.0,70.0,43.84,Paulo,26.16,37.37,2023-01
...,...,...,...,...,...,...,...,...,...,...,...,...
100994,69996,2023-12-26,Loja Rio de Janeiro 1,Mouse Pad Colorido,2,102.0,204.0,41.86,Fábio,120.28,58.96,2023-12
100995,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,4,270.0,1080.0,247.67,Fábio,89.32,8.27,2023-12
100996,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,1,87.0,87.0,79.80,Fábio,7.20,8.28,2023-12
100997,69997,2023-12-26,Loja João Pessoa,HD SSD Kingston 1 Tb,1,108.0,108.0,96.30,Marcus,11.70,10.83,2023-12
100998,69997,2023-12-26,Loja João Pessoa,Mouse Pad Colorido,2,133.0,266.0,54.58,Marcus,156.84,58.96,2023-12

In [695]:
df_final['ano - mes'] = df_final['data'].dt.to_period('M')
fat_mes = df_final.groupby('ano - mes')['valor_final'].sum().reset_index()

fat_mes['ano - mes'] = fat_mes['ano - mes'].dt.to_timestamp()

fig = px.line(fat_mes, x='ano - mes', y='valor_final', line_shape='spline', markers='1')
fig.show()

In [694]:
# Quais foram os produtos mais vendidos por cada gerente? Grafico de arvore

top_pro_gerentes = df_final.groupby(['gerente','produto'])['quantidade'].sum().reset_index().sort_values(by='quantidade')

fig = px.treemap(top_pro_gerentes, path=[px.Constant('Gerentes'),'gerente','produto'], values='quantidade')
fig.show()