In [ ]:
import pandas as pd
import plotly.express

In [ ]:
df_cafeteria = pd.read_csv('/content/drive/MyDrive/DATA PYHON 2604/Cafeteria/Cafeteria.csv')
display(df_cafeteria)

,ID da Transação,Item,Quantidade,Preço Unitário,Total Gasto,Método de Pagamento,Localização,Data da Transação
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
# Quantidade de Linhas e Colunas

df_cafeteria.shape

(10000, 8)

In [ ]:
# Verificação de Tipos de Dados e Colunas

df_cafeteria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID da Transação      10000 non-null  object
 1   Item                 9667 non-null   object
 2   Quantidade           9862 non-null   object
 3   Preço Unitário       9821 non-null   object
 4   Total Gasto          9827 non-null   object
 5   Método de Pagamento  7421 non-null   object
 6   Localização          6735 non-null   object
 7   Data da Transação    9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
# Verificação de Nulos

df_cafeteria.isnull().sum()

ID da Transação           0
Item                    333
Quantidade              138
Preço Unitário          179
Total Gasto             173
Método de Pagamento    2579
Localização            3265
Data da Transação       159
dtype: int64

In [ ]:
# Verificação de Valores Únicos por Linha

df_cafeteria.nunique()

ID da Transação        10000
Item                      10
Quantidade                 7
Preço Unitário             8
Total Gasto               19
Método de Pagamento        5
Localização                4
Data da Transação        367
dtype: int64

In [ ]:
# descrição dos campos

df_cafeteria.describe()

,ID da Transação,Item,Quantidade,Preço Unitário,Total Gasto,Método de Pagamento,Localização,Data da Transação
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [ ]:
display(df_cafeteria['Item'].value_counts())

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [ ]:
display(df_cafeteria['Quantidade'].value_counts())

Quantidade
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

In [ ]:
display(df_cafeteria['Preço Unitário'].value_counts())

Preço Unitário
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64

In [ ]:
display(df_cafeteria['Total Gasto'].value_counts())

Total Gasto
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

In [ ]:
display(df_cafeteria['Método de Pagamento'].value_counts())

Método de Pagamento
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [ ]:
display(df_cafeteria['Localização'].value_counts())

Localização
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [ ]:
# Tratamento de Dados

# Forçar a conversão das colunas para números (o que for erro vira NaN)

colunas_numericas = ['Quantidade','Preço Unitário', 'Total Gasto']
for col in colunas_numericas:
    df_cafeteria[col] = pd.to_numeric(df_cafeteria[col], errors='coerce')

In [ ]:
df_cafeteria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID da Transação      10000 non-null  object
 1   Item                 9667 non-null   object
 2   Quantidade           9521 non-null   float64
 3   Preço Unitário       9467 non-null   float64
 4   Total Gasto          9498 non-null   float64
 5   Método de Pagamento  7421 non-null   object
 6   Localização          6735 non-null   object
 7   Data da Transação    9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [ ]:
# Aplicar a regra de três vias para preencher os buracos (NaN)

df_cafeteria['Total Gasto'] = df_cafeteria['Total Gasto'].fillna(df_cafeteria['Quantidade'] * df_cafeteria['Preço Unitário'])
df_cafeteria['Preço Unitário'] = df_cafeteria['Preço Unitário'].fillna(df_cafeteria['Total Gasto'] / df_cafeteria['Quantidade'])
df_cafeteria['Quantidade'] = df_cafeteria['Quantidade'].fillna(df_cafeteria['Total Gasto'] / df_cafeteria['Preço Unitário'])

In [ ]:
df_cafeteria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID da Transação      10000 non-null  object
 1   Item                 9667 non-null   object
 2   Quantidade           9962 non-null   float64
 3   Preço Unitário       9962 non-null   float64
 4   Total Gasto          9960 non-null   float64
 5   Método de Pagamento  7421 non-null   object
 6   Localização          6735 non-null   object
 7   Data da Transação    9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [ ]:
df_cafeteria[colunas_numericas].isnull().sum()

Quantidade        38
Preço Unitário    38
Total Gasto       40
dtype: int64

In [ ]:
# Filtrar as linhas que possuem algum valor vazio (NaN) nas colunas númericas

linhas_vazias = df_cafeteria[df_cafeteria[colunas_numericas].isnull().any(axis=1)]
display(linhas_vazias)

,ID da Transação,Item,Quantidade,Preço Unitário,Total Gasto,Método de Pagamento,Localização,Data da Transação
65,TXN_4987129,Sandwich,3.0,NaN,NaN,NaN,In-store,2023-10-20
236,TXN_8562645,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-18
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15
629,TXN_9289174,Cake,NaN,NaN,12.0,Digital Wallet,In-store,2023-12-30
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17
738,TXN_8696094,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-05-14
912,TXN_1575608,Sandwich,NaN,NaN,20.0,ERROR,Takeaway,2023-01-05
1008,TXN_7225428,Tea,NaN,NaN,3.0,Credit Card,Takeaway,2023-03-07
1436,TXN_7590801,Tea,NaN,NaN,6.0,Cash,Takeaway,ERROR
1482,TXN_3593060,Smoothie,NaN,NaN,16.0,Cash,NaN,2023-03-05
1674,TXN_9367492,Tea,2.0,NaN,NaN,Cash,In-store,2023-06-19
1761,TXN_3611851,NaN,4.0,NaN,NaN,Credit Card,NaN,2023-02-09
2229,TXN_8498613,Sandwich,2.0,NaN,NaN,NaN,NaN,2023-11-08
2289,TXN_7524977,UNKNOWN,4.0,NaN,NaN,ERROR,NaN,2023-12-09
2330,TXN_3849488,Salad,NaN,NaN,5.0,NaN,In-store,2023-03-01
2585,TXN_1259340,Tea,3.0,NaN,NaN,Digital Wallet,NaN,2023-02-24
2796,TXN_9188692,Cake,NaN,3.0,NaN,Credit Card,NaN,2023-12-01
3162,TXN_3577949,Cake,3.0,NaN,NaN,ERROR,Takeaway,2023-04-25
3203,TXN_4565754,Smoothie,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,NaN,2.0,NaN,NaN,NaN,2023-04-07
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25
3598,TXN_2857444,Smoothie,1.0,NaN,NaN,Cash,Takeaway,2023-05-10
3635,TXN_6177081,Cookie,NaN,NaN,1.0,Cash,ERROR,2023-07-26
3673,TXN_6500126,Smoothie,2.0,NaN,NaN,NaN,UNKNOWN,NaN
3779,TXN_7376255,UNKNOWN,NaN,NaN,25.0,NaN,In-store,2023-05-27
4021,TXN_6424202,Cookie,2.0,NaN,NaN,Credit Card,In-store,2023-11-20
4152,TXN_9646000,ERROR,2.0,NaN,NaN,NaN,In-store,2023-12-14
4257,TXN_6470865,Coffee,NaN,2.0,NaN,Digital Wallet,Takeaway,2023-09-18
5639,TXN_6206792,Tea,NaN,NaN,6.0,Credit Card,NaN,2023-10-13
5841,TXN_5884081,Cookie,NaN,1.0,NaN,Digital Wallet,In-store,2023-07-05
5845,TXN_8388462,Smoothie,NaN,NaN,8.0,UNKNOWN,Takeaway,2023-08-19
6225,TXN_6859249,Cookie,NaN,NaN,2.0,NaN,UNKNOWN,NaN
6661,TXN_5308047,Cookie,NaN,NaN,1.0,Credit Card,NaN,2023-10-28
6674,TXN_3071092,Coffee,NaN,NaN,4.0,ERROR,NaN,2023-09-08
7029,TXN_4628338,Coffee,NaN,2.0,NaN,Cash,NaN,2023-12-25
7035,TXN_8872984,Salad,5.0,NaN,NaN,Credit Card,In-store,2023-08-23
7230,TXN_5118799,Cookie,2.0,NaN,NaN,Cash,Takeaway,2023-04-23
7244,TXN_2253622,Sandwich,5.0,NaN,NaN,Digital Wallet,Takeaway,2023-09-30
7297,TXN_9944500,Smoothie,NaN,4.0,NaN,Cash,In-store,2023-01-03
7568,TXN_3705445,Cookie,5.0,NaN,NaN,Cash,In-store,2023-09-13
7597,TXN_1082717,ERROR,NaN,NaN,9.0,Digital Wallet,In-store,2023-12-13
7686,TXN_6905143,Coffee,5.0,NaN,NaN,Cash,ERROR,2023-08-09
8021,TXN_2428781,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-09
8128,TXN_6105807,Smoothie,3.0,NaN,NaN,Credit Card,Takeaway,2023-01-18
8443,TXN_2023651,Sandwich,NaN,4.0,NaN,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,NaN,2.0,NaN,NaN,ERROR,2023-06-03
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-09-11
8497,TXN_1525583,Sandwich,3.0,NaN,NaN,Cash,Takeaway,2023-05-20
8574,TXN_2546684,Juice,NaN,3.0,NaN,Digital Wallet,Takeaway,2023-04-08
8669,TXN_7764304,Cake,NaN,NaN,3.0,Credit Card,Takeaway,2023-01-09
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04
8975,TXN_8077367,Tea,NaN,NaN,7.5,Credit Card,NaN,2023-02-27
9212,TXN_7322317,Tea,1.0,NaN,NaN,NaN,NaN,2023-03-16
9464,TXN_5744797,Cake,NaN,NaN,3.0,Cash,In-store,2023-12-20
9590,TXN_9924732,Sandwich,NaN,4.0,NaN,Credit Card,In-store,2023-01-18
9819,TXN_1208561,NaN,NaN,NaN,20.0,Credit Card,NaN,2023-08-19
9869,TXN_1975184,Coffee,NaN,2.0,NaN,Digital Wallet,NaN,2023-01-15
9893,TXN_3809533,Juice,2.0,NaN,NaN,Digital Wallet,Takeaway,2023-02-02

In [ ]:
display(df_cafeteria['Item'].value_counts())

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [ ]:
# Pegar colunas Item e Preço, remover os vazios e mostrar os valores únicos

tabela_de_precos = df_cafeteria[['Item','Preço Unitário']].dropna().drop_duplicates()
display(tabela_de_precos.sort_values(by='Item'))

         Item  Preço Unitário
1        Cake             3.0
0      Coffee             2.0
2      Cookie             1.0
283     ERROR             1.0
14      ERROR             1.5
281     ERROR             2.0
216     ERROR             4.0
69      ERROR             3.0
88      ERROR             5.0
17      Juice             3.0
3       Salad             5.0
7    Sandwich             4.0
5    Smoothie             4.0
42        Tea             1.5
31    UNKNOWN             1.0
52    UNKNOWN             5.0
717   UNKNOWN             1.5
6     UNKNOWN             3.0
165   UNKNOWN             4.0
724   UNKNOWN             2.0

In [ ]:
# Criar uma tabela relacionando o Item ao Preço Unitário

tabela_de_precos = df_cafeteria[['Item','Preço Unitário']].dropna().drop_duplicates()
dicionario_precos = dict(zip(tabela_de_precos['Item'], tabela_de_precos['Preço Unitário']))

display(dicionario_precos)

{'Coffee': 2.0,
 'Cake': 3.0,
 'Cookie': 1.0,
 'Salad': 5.0,
 'Smoothie': 4.0,
 'UNKNOWN': 2.0,
 'Sandwich': 4.0,
 'ERROR': 1.0,
 'Juice': 3.0,
 'Tea': 1.5}

In [ ]:
# Usar a tabela para preencher os preços unitários que estavam faltando (NaN)

df_cafeteria['Preço Unitário'] = df_cafeteria['Preço Unitário'].fillna(df_cafeteria['Item'].map(dicionario_precos))

In [ ]:
df_cafeteria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID da Transação      10000 non-null  object
 1   Item                 9667 non-null   object
 2   Quantidade           9962 non-null   float64
 3   Preço Unitário       9998 non-null   float64
 4   Total Gasto          9960 non-null   float64
 5   Método de Pagamento  7421 non-null   object
 6   Localização          6735 non-null   object
 7   Data da Transação    9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [ ]:
prod_qtd = df.groupby('Item')['Quantidade'].sum().sort_values( ascending=False).reset_index()
fig = px.bar(
    prod_qtd,
    x='Item',
    y='Quantidade',
    text=prod_qtd['Quantidade'],
    title='Vendas por produtos em quantidade',
    color='Item',
    color_discrete_sequence= px.colors.carto.Redor_r
)


fig.update_traces(
    textposition='outside',
    texttemplate='%{text:.3s}'
)


fig.show()

NameError: name 'df' is not defined

In [ ]:
prod_rec = df.groupby('Item')['Total Gasto'].sum().sort_values(ascending=False).reset_index().head()


fig = px.bar(
    prod_rec,
    x = 'Item',
    y='Total Gasto',
    text=prod_rec['Total Gasto'],
    color='Total Gasto',
    color_continuous_scale= px.colors.carto.Redor,
    title='Receita por produto'
)


fig.update_traces(textposition='outside', texttemplate='$ %{text:0.2s}')


fig.show()

NameError: name 'df' is not defined